# Generated by Django 3.0.3 on 2020-02-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('right', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('rights', models.ManyToManyField(related_name='roles', to='users.Rights')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=500, null=True)),
                ('user_surname', models.CharField(max_length=500, null=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_registration_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('role', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Roles')),
            ],
        ),
    ]
