# Generated by Django 3.0.3 on 2020-02-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200227_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rights',
            new_name='Right',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
