# Generated by Django 3.0.3 on 2020-02-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200227_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='rights',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.DeleteModel(
            name='Right',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
