# Generated by Django 3.0.3 on 2020-03-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200305_1834'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE auth_group SET name='Manager' WHERE name='Mgr';"
        )
    ]
